### ISSUE TITLE
System.getProperty("platform") result=null

### ISSUE THREAD

**Issue by zzm-note** [appium-boneyard/sample-code#165]
**path**
sample-code\examples\java\junit\src\test\java\com\saucelabs\appium\BaseCrossPlatformDriver.java
**Line 35**
catch InvocationTargetException
![image](https://user-images.githubusercontent.com/25860330/43899981-22953cc4-9c16-11e8-9e96-534b1c96c581.png)

**Comment by imurchie** [comment]
https://github.com/appium/appium/tree/master/sample-code/java
