### ISSUE TITLE
no reset not working

### ISSUE THREAD

**Issue by SpiritComan** [appium-boneyard/sample-code#168]
here is my set for appium: Capabilities {appActivity: com.whatsapp.HomeActivity , appPackage: com.whatsapp, databaseEnabled: false, desired: {appActivity: com.whatsapp.HomeActivity , appPackage: com.whatsapp, deviceName: 192.168.244.101:5555 , fullReset: false, noReset: true, platformName: android, platformVersion: 5.0}, deviceManufacturer: unknown, deviceModel: S2, deviceName: 192.168.244.101:5555, deviceScreenSize: 1440x2560, deviceUDID: 192.168.244.101:5555, fullReset: false, javascriptEnabled: true, locationContextEnabled: false, networkConnectionEnabled: true, noReset: true, platform: LINUX, platformName: Android, platformVersion: 5.0, takesScreenshot: true, warnings: {}, webStorageEnabled: false},but it not working.can anyone tell me why?

**Comment by imurchie** [comment]
This repository is no longer being monitored. The sample code now exists in https://github.com/appium/appium/tree/master/sample-code. Please create an issue, with all the information requested (including what language you are using and what part of the sample code you are trying out) here: https://github.com/appium/appium/issues/new
